services:
  cups:
    build: .
    container_name: cups-print-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - CUPSADMIN=${CUPS_ADMIN_USER:-admin}
      - CUPSPASSWORD=${CUPS_ADMIN_PASSWORD:-admin}
    volumes:
      - ./cups/printers.conf:/etc/cups/printers.conf:ro
      - ./cups/cupsd.conf:/etc/cups/cupsd.conf:ro
      - ./cups/cups-files.conf:/etc/cups/cups-files.conf:ro
      # Persist CUPS runtime, cache and logs on the host so they are visible
      # and survive container recreation. These map to ./data/* relative to
      # the repository root on the host (create these dirs before starting).
      - ./data/cups:/var/spool/cups
      - ./data/cache:/var/cache/cups
      - ./data/logs:/var/log/cups
    devices:
      - /dev/bus/usb:/dev/bus/usb
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - "com.raspberry-pi.print-server=true"

# Using host directories for CUPS data/cache/logs (see service volumes).
# If you prefer Docker named volumes, you can re-enable them here.
